# Generated by Django 4.2.2 on 2023-06-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='profiles/images'),
        ),
    ]
