# Generated by Django 4.2.2 on 2023-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_alter_article_options_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='choose an image in right size.', upload_to='images/articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
